# Homeserver URL to resolve aliases with.
homeserver_url: https://matrix-client.matrix.org
# Alias mapping. The key is the local alias, the value is the alias that's resolved to get the room ID and server list.
aliases:
    "#matrix:example.com": "#matrix:matrix.org"
# Pattern mappings. The key is a regular expression (RE2 syntax) and the value is a replacement.
# If an alias doesn't match any of the static mappings, each pattern here is tested in order. The first matching regex
# is used to replace the input alias with the replacement here, and the result is resolved to get the room ID.
patterns:
    "^#(.+):freenode.net$": "#freenode_#$1:matrix.org"
# How long (in seconds) should resolved room IDs and server lists be cached?
cache_ttl: 3600
# IP and port to listen on
listen: :8008
# What address to serve in the /.well-known/matrix/server file
server_well_known: example.com:443
# Optionally, server names and signing keys to respond to /_matrix/key/v2/server
server_keys:
    # The key is the Host header that mauliasproxy should expect.
    # `default` is used for everything that doesn't match another key.
    default:
        # The server name to respond with. Optional, defaults to host.
        server_name: example.com
        # The signing key to use in Synapse format (`ed25519 keyid base64key`)
        # Can be set to `env:NAME` to read the value from `NAME` in the environment.
        # A random key can be generated with `mauliasproxy genkey`
        signing_key: ed25519 0 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
